config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {:registrations => "users/registrations"}

  # get '/users/sign_out' => 'devise/sessions#destroy'
  resources :application_forms
  root to: 'application_forms#index'

  resources :invoices, only: [:index, :show]

  resources :statistics do
    delete :delete_excel_attachment
    get    :result_excel_analysis
  end

end

app/controllers/application_forms_controller.rb
class ApplicationFormsController < ApplicationController
  before_action :set_application_form, only: [:show, :edit, :update, :destroy]

  # GET /application_forms
  # GET /application_forms.json
  def index
    if current_user.email == "admin@pjtsau.com"
      @application_forms = ApplicationForm.all
    else
      # @application_forms = current_user.application_forms
    end
    respond_to do |format|
      format.html
      format.csv { send_data @application_forms.to_csv, filename: "application_forms-#{Date.today}.csv" }
      format.xls
    end
  end

  # GET /application_forms/1
  # GET /application_forms/1.json
  def show
  end

  # GET /application_forms/new
  def new
    @application_form = ApplicationForm.new
  end

  # GET /application_forms/1/edit
  def edit
  end

  # POST /application_forms
  # POST /application_forms.json
  def create
    @application_form = ApplicationForm.new(application_form_params)
    @application_form.user_id = current_user.id
    respond_to do |format|
      if @application_form.save
        format.html { redirect_to root_path, notice: 'Application form was successfully created.' }
        format.json { render :show, status: :created, location: @application_form }
      else
        format.html { render :new }
        format.json { render json: @application_form.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /application_forms/1
  # PATCH/PUT /application_forms/1.json
  def update
    @application_form.user_id = current_user.id
    respond_to do |format|
      if @application_form.update(application_form_params)
        format.html { redirect_to root_path, notice: 'Application form was successfully updated.' }
        format.json { render :show, status: :ok, location: @application_form }
      else
        format.html { render :edit }
        format.json { render json: @application_form.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /application_forms/1
  # DELETE /application_forms/1.json
  def destroy
    @application_form.destroy
    respond_to do |format|
      format.html { redirect_to application_forms_url, notice: 'Application form was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_application_form
      @application_form = ApplicationForm.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def application_form_params
      params.require(:application_form).permit(:mobile_number, :application_number, :hall_ticket_number, :rank, :name, :gender, :date_of_birth, :age, :aadhaar_number, :blood_group, :mother_name, :father_name, :mobile_number1, :mobile_number2, :email, :social_status, :religion, :nationality, :physically_challenged, :address, :state, :pincode, :place_of_study_vi_to_xii, :physically_challenged_category, :sports_category, :defence_category, :ncc_category, :farmers_quota)
    end
end

app/helpers/application_forms_helper.rb
module ApplicationFormsHelper
end

app/views/application_forms/_form.html.erb
<%= form_with(model: application_form, local: true) do |form| %>
  <% if application_form.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(application_form.errors.count, "error") %> prohibited this application_form from being saved:</h2>

      <ul>
      <% application_form.errors.full_messages.each do |message| %>
        <!-- <li><%#= message %></li> -->
        <div class="alert alert-danger d-none"><%= message %></div>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group row">
    <label for="exampleInputName" class="col-sm-3 col-form-label">Mobile No</label>
    <div class="col-sm-9">
      <%= form.text_field :mobile_number, class: 'form-control' %>
      <div class="invalid-feedback">Mobile number can't be blank</div>
      <div class="valid-feedback">Looks good!</div>
      <!-- <small class="form-text text-muted">Text input example</small> -->
    </div>
  </div>

  <div class="form-group row">
    <label for="exampleInputName" class="col-sm-3 col-form-label">Application number</label>
    <div class="col-sm-9">
      <%= form.text_field :application_number, class: 'form-control' %>
      <div class="invalid-feedback">Mobile number can't be blank</div>
      <div class="valid-feedback">Looks good!</div>
      <!-- <small class="form-text text-muted">Text input example</small> -->
    </div>
  </div>

  <div class="form-group row">
    <label for="exampleInputName" class="col-sm-3 col-form-label">Hall ticket number</label>
    <div class="col-sm-9">
      <%= form.text_field :hall_ticket_number, class: 'form-control' %>
      <div class="invalid-feedback">Mobile number can't be blank</div>
      <div class="valid-feedback">Looks good!</div>
      <!-- <small class="form-text text-muted">Text input example</small> -->
    </div>
  </div>

  <div class="form-group row">
    <label for="exampleInputName" class="col-sm-3 col-form-label">Rank</label>
    <div class="col-sm-9">
      <%= form.number_field :rank, class: 'form-control' %>
      <div class="invalid-feedback">Mobile number can't be blank</div>
      <div class="valid-feedback">Looks good!</div>
      <!-- <small class="form-text text-muted">Text input example</small> -->
    </div>
  </div>

  <div class="form-group row">
    <label for="exampleInputName" class="col-sm-3 col-form-label">Name</label>
    <div class="col-sm-9">
      <%= form.text_field :name, class: 'form-control' %>
      <div class="invalid-feedback">Mobile number can't be blank</div>
      <div class="valid-feedback">Looks good!</div>
      <!-- <small class="form-text text-muted">Text input example</small> -->
    </div>
  </div>

  <div class="form-group row">
    <label for="exampleInputName" class="col-sm-3 col-form-label">Gender</label>
    <div class="col-sm-9">
      <%= form.text_field :gender, class: 'form-control' %>
      <div class="invalid-feedback">Mobile number can't be blank</div>
      <div class="valid-feedback">Looks good!</div>
      <!-- <small class="form-text text-muted">Text input example</small> -->
    </div>
  </div>

  <div class="form-group row">
    <label for="exampleInputName" class="col-sm-3 col-form-label">Date of birth</label>
    <div class="col-sm-9">
      <%= form.date_select :date_of_birth, class: 'form-control' %>
      <div class="invalid-feedback">Mobile number can't be blank</div>
      <div class="valid-feedback">Looks good!</div>
      <!-- <small class="form-text text-muted">Text input example</small> -->
    </div>
  </div>

  <div class="form-group row">
    <label for="exampleInputName" class="col-sm-3 col-form-label">Age</label>
    <div class="col-sm-9">
      <%= form.number_field :age, class: 'form-control' %>
      <div class="invalid-feedback">Mobile number can't be blank</div>
      <div class="valid-feedback">Looks good!</div>
      <!-- <small class="form-text text-muted">Text input example</small> -->
    </div>
  </div>

  <div class="form-group row">
    <label for="exampleInputName" class="col-sm-3 col-form-label">Aadhaar number</label>
    <div class="col-sm-9">
      <%= form.text_field :aadhaar_number, class: 'form-control' %>
      <div class="invalid-feedback">Mobile number can't be blank</div>
      <div class="valid-feedback">Looks good!</div>
      <!-- <small class="form-text text-muted">Text input example</small> -->
    </div>
  </div>

  <div class="form-group row">
    <label for="exampleInputName" class="col-sm-3 col-form-label">Blood group</label>
    <div class="col-sm-9">
      <%= form.text_field :blood_group, class: 'form-control' %>
      <div class="invalid-feedback">Mobile number can't be blank</div>
      <div class="valid-feedback">Looks good!</div>
      <!-- <small class="form-text text-muted">Text input example</small> -->
    </div>
  </div>

  <div class="form-group row">
    <label for="exampleInputName" class="col-sm-3 col-form-label">Mother name</label>
    <div class="col-sm-9">
      <%= form.text_field :mother_name, class: 'form-control' %>
      <div class="invalid-feedback">Mobile number can't be blank</div>
      <div class="valid-feedback">Looks good!</div>
      <!-- <small class="form-text text-muted">Text input example</small> -->
    </div>
  </div>

  <div class="form-group row">
    <label for="exampleInputName" class="col-sm-3 col-form-label">Father name</label>
    <div class="col-sm-9">
      <%= form.text_field :father_name, class: 'form-control' %>
      <div class="invalid-feedback">Mobile number can't be blank</div>
      <div class="valid-feedback">Looks good!</div>
      <!-- <small class="form-text text-muted">Text input example</small> -->
    </div>
  </div>

  <div class="form-group row">
    <label for="exampleInputName" class="col-sm-3 col-form-label">Mobile number1</label>
    <div class="col-sm-9">
      <%= form.text_field :mobile_number1, class: 'form-control' %>
      <div class="invalid-feedback">Mobile number can't be blank</div>
      <div class="valid-feedback">Looks good!</div>
      <!-- <small class="form-text text-muted">Text input example</small> -->
    </div>
  </div>

  <div class="form-group row">
    <label for="exampleInputName" class="col-sm-3 col-form-label">Mobile number2</label>
    <div class="col-sm-9">
      <%= form.text_field :mobile_number2, class: 'form-control' %>
      <div class="invalid-feedback">Mobile number can't be blank</div>
      <div class="valid-feedback">Looks good!</div>
      <!-- <small class="form-text text-muted">Text input example</small> -->
    </div>
  </div>

  <div class="form-group row">
    <label for="exampleInputName" class="col-sm-3 col-form-label">Email</label>
    <div class="col-sm-9">
      <%= form.text_field :email, class: 'form-control' %>
      <div class="invalid-feedback">Mobile number can't be blank</div>
      <div class="valid-feedback">Looks good!</div>
      <!-- <small class="form-text text-muted">Text input example</small> -->
    </div>
  </div>

  <div class="form-group row">
    <label for="exampleInputName" class="col-sm-3 col-form-label">Social status</label>
    <div class="col-sm-9">
      <%= form.text_field :social_status, class: 'form-control' %>
      <div class="invalid-feedback">Mobile number can't be blank</div>
      <div class="valid-feedback">Looks good!</div>
      <!-- <small class="form-text text-muted">Text input example</small> -->
    </div>
  </div>

  <div class="form-group row">
    <label for="exampleInputName" class="col-sm-3 col-form-label">Religion</label>
    <div class="col-sm-9">
      <%= form.text_field :religion, class: 'form-control' %>
      <div class="invalid-feedback">Mobile number can't be blank</div>
      <div class="valid-feedback">Looks good!</div>
      <!-- <small class="form-text text-muted">Text input example</small> -->
    </div>
  </div>

  <div class="form-group row">
    <label for="exampleInputName" class="col-sm-3 col-form-label">Nationality</label>
    <div class="col-sm-9">
      <%= form.text_field :nationality, class: 'form-control' %>
      <div class="invalid-feedback">Mobile number can't be blank</div>
      <div class="valid-feedback">Looks good!</div>
      <!-- <small class="form-text text-muted">Text input example</small> -->
    </div>
  </div>

  <div class="form-group row">
    <label for="exampleInputName" class="col-sm-3 col-form-label">Physically challenged</label>
    <div class="col-sm-9">
      <%= form.check_box :physically_challenged, class: '' %>
      <div class="invalid-feedback">Mobile number can't be blank</div>
      <div class="valid-feedback">Looks good!</div>
      <!-- <small class="form-text text-muted">Text input example</small> -->
    </div>
  </div>

  <div class="form-group row">
    <label for="exampleInputName" class="col-sm-3 col-form-label">Address</label>
    <div class="col-sm-9">
      <%= form.text_field :address, class: 'form-control' %>
      <div class="invalid-feedback">Mobile number can't be blank</div>
      <div class="valid-feedback">Looks good!</div>
      <!-- <small class="form-text text-muted">Text input example</small> -->
    </div>
  </div>

  <div class="form-group row">
    <label for="exampleInputName" class="col-sm-3 col-form-label">State</label>
    <div class="col-sm-9">
      <%= form.text_field :state, class: 'form-control' %>
      <div class="invalid-feedback">Mobile number can't be blank</div>
      <div class="valid-feedback">Looks good!</div>
      <!-- <small class="form-text text-muted">Text input example</small> -->
    </div>
  </div>

  <div class="form-group row">
    <label for="exampleInputName" class="col-sm-3 col-form-label">Pincode</label>
    <div class="col-sm-9">
      <%= form.text_field :pincode, class: 'form-control' %>
      <div class="invalid-feedback">Mobile number can't be blank</div>
      <div class="valid-feedback">Looks good!</div>
      <!-- <small class="form-text text-muted">Text input example</small> -->
    </div>
  </div>

  <div class="form-group row">
    <label for="exampleInputName" class="col-sm-3 col-form-label">Place of study vi to xii</label>
    <div class="col-sm-9">
      <%= form.text_field :place_of_study_vi_to_xii, class: 'form-control' %>
      <div class="invalid-feedback">Mobile number can't be blank</div>
      <div class="valid-feedback">Looks good!</div>
      <!-- <small class="form-text text-muted">Text input example</small> -->
    </div>
  </div>

  <div class="form-group row">
    <label for="exampleInputName" class="col-sm-3 col-form-label">Physically challenged category</label>
    <div class="col-sm-9">
      <%= form.text_field :physically_challenged_category, class: 'form-control' %>
      <div class="invalid-feedback">Mobile number can't be blank</div>
      <div class="valid-feedback">Looks good!</div>
      <!-- <small class="form-text text-muted">Text input example</small> -->
    </div>
  </div>

  <div class="form-group row">
    <label for="exampleInputName" class="col-sm-3 col-form-label">Sports category</label>
    <div class="col-sm-9">
      <%= form.text_field :sports_category, class: 'form-control' %>
      <div class="invalid-feedback">Mobile number can't be blank</div>
      <div class="valid-feedback">Looks good!</div>
      <!-- <small class="form-text text-muted">Text input example</small> -->
    </div>
  </div>

  <div class="form-group row">
    <label for="exampleInputName" class="col-sm-3 col-form-label">Defence category</label>
    <div class="col-sm-9">
      <%= form.text_field :defence_category, class: 'form-control' %>
      <div class="invalid-feedback">Mobile number can't be blank</div>
      <div class="valid-feedback">Looks good!</div>
      <!-- <small class="form-text text-muted">Text input example</small> -->
    </div>
  </div>

  <div class="form-group row">
    <label for="exampleInputName" class="col-sm-3 col-form-label">Ncc category</label>
    <div class="col-sm-9">
      <%= form.text_field :ncc_category, class: 'form-control' %>
      <div class="invalid-feedback">Mobile number can't be blank</div>
      <div class="valid-feedback">Looks good!</div>
      <!-- <small class="form-text text-muted">Text input example</small> -->
    </div>
  </div>

  <div class="form-group row">
    <label for="exampleInputName" class="col-sm-3 col-form-label">Farmers quota</label>
    <div class="col-sm-9">
      <%= form.text_field :farmers_quota, class: 'form-control' %>
      <div class="invalid-feedback">Mobile number can't be blank</div>
      <div class="valid-feedback">Looks good!</div>
      <!-- <small class="form-text text-muted">Text input example</small> -->
    </div>
  </div>

  <div class="form-group row mb-0">
    <div class="col-sm-9 offset-sm-3">
      <button type="submit" class="btn btn-primary">Apply</button>
      <%= link_to 'Back', application_forms_path, class: "btn btn-outline-secondary" %>

      <!-- <button type="reset" class="btn btn-outline-secondary">Cancel</button> -->
    </div>
  </div>

<% end %>

app/views/application_forms/edit.html.erb
<div class="invoice-box">
<center>
<h1 style="float: center;">Editing Application Form</h1>
</center>
<br>
<%= render 'form', application_form: @application_form %>

<%= link_to 'Show', @application_form %>
</div>
<%#= link_to 'Back', application_forms_path %>

app/views/application_forms/index.html.erb
<div class="invoice-box">
  <p id="notice"><%#= notice %></p>

  <%#= link_to 'Edit', edit_application_form_path(application_form), class: 'btn btn-info' %>
  <% if current_user.email == "admin@pjtsau.com" %>
    <div class="row">
      <label for="exampleInputName" class="col-sm-5"><h1>Applications list</h1></label>
      <div class="col-sm-7" style="text-align: right;">
        <%= link_to "Download to CSV", application_forms_path(format: "csv"), :class => "btn btn-info" %>
        <%= link_to "Download to Excel", application_forms_path(format: "xls"), :class => "btn btn-info" %>
      </div>
    </div>
    <table id="adding_datatable" class="table table-bordered table-condensed">
      <thead>
        <tr>
          <th>Rank</th>
          <th>Application no</th>
          <th>H no</th>
          <th>Name</th>
          <th>Email</th>
          <th>Mobile number</th>
          <th>Address</th>
          <th>Actions</th>
        </tr>
      </thead>

      <tbody>
        <% @application_forms.each do |application_form| %>
        <tr>
          <td><%= application_form.rank %></td>
          <td><%= application_form.application_number %></td>
          <td><%= application_form.hall_ticket_number %></td>
          <td><%= application_form.name %></td>
          <td><%= application_form.email %></td>
          <td><%= application_form.mobile_number1 %></td>
          <td><%= application_form.address %></td>
          <td><%= link_to 'Show', application_form, class: 'btn btn-info' %>
          <%= link_to 'Edit', edit_application_form_path(application_form), class: 'btn btn-info' %>
          <%= link_to 'Destroy', application_form, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-info' %></td>
        </tr>
        <% end %>
      </tbody>
    </table><br>
  <% else %>
    <div class="row">
      <div class="col-sm-12" style="text-align: center;">
        <%= link_to ' + New Application Form', new_application_form_path, class: 'btn btn-primary' %>
        <%= link_to "NOTIFICATION", 'schedule.pdf', :class => "btn btn-info", target: '_blank' %>
        <%= link_to "PROSPECTUS", 'prospectus.pdf', :class => "btn btn-info", target: '_blank' %>
        <%= link_to "FORM-I", 'form_1.pdf', :class => "btn btn-info", target: '_blank' %>
        <%= link_to "FORM-II", 'form_2.pdf', :class => "btn btn-info", target: '_blank' %>
        <%= link_to "INSTRUCTIONS", 'Instructions_for_applicants.pdf', :class => "btn btn-info", target: '_blank' %>
      </div>
    </div><br>
  <% end %>
</div>
<!-- <table>
  <thead>
    <tr>
      <th>Mobile number</th>
      <th>Application number</th>
      <th>Hall ticket number</th>
      <th>Rank</th>
      <th>Name</th>
      <th>Gender</th>
      <th>Date of birth</th>
      <th>Age</th>
      <th>Aadhaar number</th>
      <th>Blood group</th>
      <th>Mother name</th>
      <th>Father name</th>
      <th>Mobile number1</th>
      <th>Mobile number2</th>
      <th>Email</th>
      <th>Social status</th>
      <th>Religion</th>
      <th>Nationality</th>
      <th>Physically challenged</th>
      <th>Address</th>
      <th>State</th>
      <th>Pincode</th>
      <th>Place of study vi to xii</th>
      <th>Physically challenged category</th>
      <th>Sports category</th>
      <th>Defence category</th>
      <th>Ncc category</th>
      <th>Farmers quota</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <%# @application_forms.each do |application_form| %>
      <tr>
        <td><%#= application_form.mobile_number %></td>
        <td><%#= application_form.application_number %></td>
        <td><%#= application_form.hall_ticket_number %></td>
        <td><%#= application_form.rank %></td>
        <td><%#= application_form.name %></td>
        <td><%#= application_form.gender %></td>
        <td><%#= application_form.date_of_birth %></td>
        <td><%#= application_form.age %></td>
        <td><%#= application_form.aadhaar_number %></td>
        <td><%#= application_form.blood_group %></td>
        <td><%#= application_form.mother_name %></td>
        <td><%#= application_form.father_name %></td>
        <td><%#= application_form.mobile_number1 %></td>
        <td><%#= application_form.mobile_number2 %></td>
        <td><%#= application_form.email %></td>
        <td><%#= application_form.social_status %></td>
        <td><%#= application_form.religion %></td>
        <td><%#= application_form.nationality %></td>
        <td><%#= application_form.physically_challenged %></td>
        <td><%#= application_form.address %></td>
        <td><%#= application_form.state %></td>
        <td><%#= application_form.pincode %></td>
        <td><%#= application_form.place_of_study_vi_to_xii %></td>
        <td><%#= application_form.physically_challenged_category %></td>
        <td><%#= application_form.sports_category %></td>
        <td><%#= application_form.defence_category %></td>
        <td><%#= application_form.ncc_category %></td>
        <td><%#= application_form.farmers_quota %></td>
        <td><%#= link_to 'Show', application_form %></td>
        <td><%#= link_to 'Edit', edit_application_form_path(application_form) %></td>
        <td><%#= link_to 'Destroy', application_form, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <%# end %>
  </tbody>
</table> -->

<script>
$(document).ready(function () {
  $('#adding_datatable').DataTable({
    "bPaginate": true,
  });
});
</script>

app/views/application_forms/index.xls.erb
<table border="1">
  <tr>
    <th>mobile_number</th>
    <th>application_number</th>
    <th>hall_ticket_number</th>
    <th>rank</th>
    <th>name</th>
    <th>gender</th>
    <th>date_of_birth</th>
    <th>age</th>
    <th>aadhaar_number</th>
    <th>blood_group</th>
    <th>mother_name</th>
    <th>father_name</th>
    <th>mobile_number1</th>
    <th>mobile_number2</th>
    <th>email</th>
    <th>social_status</th>
    <th>religion</th>
    <th>nationality</th>
    <th>physically_challenged</th>
    <th>address</th>
    <th>state</th>
    <th>pincode</th>
    <th>place_of_study_vi_to_xii</th>
    <th>physically_challenged_category</th>
    <th>sports_category</th>
    <th>defence_category</th>
    <th>ncc_category</th>
    <th>farmers_quota</th>
    <th>created_at</th>
    <th>updated_at</th>>
  </tr>
  <% @application_forms.each do |application_form| %>
  <tr>
    <td><%= application_form.mobile_number %></td>
    <td><%= application_form.application_number %></td>
    <td><%= application_form.hall_ticket_number %></td>
    <td><%= application_form.rank %></td>
    <td><%= application_form.name %></td>
    <td><%= application_form.gender %></td>
    <td><%= application_form.date_of_birth %></td>
    <td><%= application_form.age %></td>
    <td><%= application_form.aadhaar_number %></td>
    <td><%= application_form.blood_group %></td>
    <td><%= application_form.mother_name %></td>
    <td><%= application_form.father_name %></td>
    <td><%= application_form.mobile_number1 %></td>
    <td><%= application_form.mobile_number2 %></td>
    <td><%= application_form.email %></td>
    <td><%= application_form.social_status %></td>
    <td><%= application_form.religion %></td>
    <td><%= application_form.nationality %></td>
    <td><%= application_form.physically_challenged %></td>
    <td><%= application_form.address %></td>
    <td><%= application_form.state %></td>
    <td><%= application_form.pincode %></td>
    <td><%= application_form.place_of_study_vi_to_xii %></td>
    <td><%= application_form.physically_challenged_category %></td>
    <td><%= application_form.sports_category %></td>
    <td><%= application_form.defence_category %></td>
    <td><%= application_form.ncc_category %></td>
    <td><%= application_form.farmers_quota %></td>
    <td><%= application_form.created_at %></td>
    <td><%= application_form.updated_at %></td>
  </tr>
  <% end %>
</table>

app/views/application_forms/new.html.erb
<div class="invoice-box">

<center>
<h1 style="float: center;">New Application Form</h1>
</center>
<br>
<%= render 'form', application_form: @application_form %>
</div>
<br><br>
<%#= link_to 'Back', application_forms_path %>

app/views/application_forms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Mobile number:</strong>
  <%= @application_form.mobile_number %>
</p>

<p>
  <strong>Application number:</strong>
  <%= @application_form.application_number %>
</p>

<p>
  <strong>Hall ticket number:</strong>
  <%= @application_form.hall_ticket_number %>
</p>

<p>
  <strong>Rank:</strong>
  <%= @application_form.rank %>
</p>

<p>
  <strong>Name:</strong>
  <%= @application_form.name %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @application_form.gender %>
</p>

<p>
  <strong>Date of birth:</strong>
  <%= @application_form.date_of_birth %>
</p>

<p>
  <strong>Age:</strong>
  <%= @application_form.age %>
</p>

<p>
  <strong>Aadhaar number:</strong>
  <%= @application_form.aadhaar_number %>
</p>

<p>
  <strong>Blood group:</strong>
  <%= @application_form.blood_group %>
</p>

<p>
  <strong>Mother name:</strong>
  <%= @application_form.mother_name %>
</p>

<p>
  <strong>Father name:</strong>
  <%= @application_form.father_name %>
</p>

<p>
  <strong>Mobile number1:</strong>
  <%= @application_form.mobile_number1 %>
</p>

<p>
  <strong>Mobile number2:</strong>
  <%= @application_form.mobile_number2 %>
</p>

<p>
  <strong>Email:</strong>
  <%= @application_form.email %>
</p>

<p>
  <strong>Social status:</strong>
  <%= @application_form.social_status %>
</p>

<p>
  <strong>Religion:</strong>
  <%= @application_form.religion %>
</p>

<p>
  <strong>Nationality:</strong>
  <%= @application_form.nationality %>
</p>

<p>
  <strong>Physically challenged:</strong>
  <%= @application_form.physically_challenged %>
</p>

<p>
  <strong>Address:</strong>
  <%= @application_form.address %>
</p>

<p>
  <strong>State:</strong>
  <%= @application_form.state %>
</p>

<p>
  <strong>Pincode:</strong>
  <%= @application_form.pincode %>
</p>

<p>
  <strong>Place of study vi to xii:</strong>
  <%= @application_form.place_of_study_vi_to_xii %>
</p>

<p>
  <strong>Physically challenged category:</strong>
  <%= @application_form.physically_challenged_category %>
</p>

<p>
  <strong>Sports category:</strong>
  <%= @application_form.sports_category %>
</p>

<p>
  <strong>Defence category:</strong>
  <%= @application_form.defence_category %>
</p>

<p>
  <strong>Ncc category:</strong>
  <%= @application_form.ncc_category %>
</p>

<p>
  <strong>Farmers quota:</strong>
  <%= @application_form.farmers_quota %>
</p>

<%= link_to 'Edit', edit_application_form_path(@application_form) %> |
<%= link_to 'Back', application_forms_path %>