config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {:registrations => "users/registrations"}

  # get '/users/sign_out' => 'devise/sessions#destroy'
  resources :application_forms
  root to: 'application_forms#index'

  resources :invoices, only: [:index, :show]

  resources :statistics do
    delete :delete_excel_attachment
    get    :result_excel_analysis
  end

end

app/models/statistic.rb
class Statistic < ApplicationRecord
  has_one_attached :excel_file

  require 'roo'

  def excel_calculation_part
    result = []
    file_path = ActiveStorage::Blob.service.send(:path_for, self.excel_file.key)
     xlsx = Roo::Spreadsheet.open(file_path, extension: :xlsx)
     spreadsheet = xlsx.sheet("Sheet1")
     (1..self.no_of_treatments).each do |i|
       result << spreadsheet.row(i) + [spreadsheet.row(i).sum]
     end
     result
  end
end

app/controllers/statistics_controller.rb
class StatisticsController < ApplicationController
  before_action :set_statistic, only: [:show, :edit, :update, :destroy]

  # GET /statistics
  # GET /statistics.json
  def index
    @statistics = Statistic.all
  end

  # GET /statistics/1
  # GET /statistics/1.json
  def show
    @statistic = Statistic.find(params[:id])
    @result_data = @statistic.excel_calculation_part
    respond_to do |format|
      format.html
      format.pdf do
        render pdf: "Invoice No. #{@statistic.id}",
        page_size: 'A4',
        template: "statistics/show.html.erb",
        layout: "pdf.html",
        orientation: "Landscape",
        lowquality: true,
        zoom: 1,
        dpi: 75
      end
    end
  end

  # GET /statistics/new
  def new
    @statistic = Statistic.new
  end

  # GET /statistics/1/edit
  def edit
  end

  # POST /statistics
  # POST /statistics.json
  def create
    @statistic = Statistic.new(statistic_params)

    respond_to do |format|
      if @statistic.save
        format.html { redirect_to @statistic, notice: 'Statistic was successfully created.' }
        format.json { render :show, status: :created, location: @statistic }
      else
        format.html { render :new }
        format.json { render json: @statistic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /statistics/1
  # PATCH/PUT /statistics/1.json
  def update
    respond_to do |format|
      if @statistic.update(statistic_params)
        format.html { redirect_to @statistic, notice: 'Statistic was successfully updated.' }
        format.json { render :show, status: :ok, location: @statistic }
      else
        format.html { render :edit }
        format.json { render json: @statistic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /statistics/1
  # DELETE /statistics/1.json
  def destroy
    @statistic.destroy
    respond_to do |format|
      format.html { redirect_to statistics_url, notice: 'Statistic was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def delete_excel_attachment
    @statistic = Statistic.find(params[:statistic_id])
    @statistic.excel.purge
    redirect_back(fallback_location: request.referer)
  end

  def result_excel_analysis
    # binding.pry
    @statistic = Statistic.find(params[:statistic_id])
    @statistic.abc
    # respond_to do |format|
    #   format.html { redirect_to statistics_url, notice: 'Statistic was successfully destroyed.' }
    #   format.json { head :no_content }
    # end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_statistic
      @statistic = Statistic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def statistic_params
      params.require(:statistic).permit(:no_of_treatments, :no_of_samples, :analytical_type, :excel_file)
    end
end

app/helpers/statistics_helper.rb
module StatisticsHelper
end

app/views/statistics/_form.html.erb
<%= form_with(model: statistic, local: true) do |form| %>
  <% if statistic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(statistic.errors.count, "error") %> prohibited this statistic from being saved:</h2>

      <ul>
      <% statistic.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :no_of_treatments %>
    <%= form.number_field :no_of_treatments %>
  </div>

  <div class="field">
    <%= form.label :no_of_samples %>
    <%= form.number_field :no_of_samples %>
  </div>

  <div class="field">
    <%= form.label :analytical_type %>
    <%= form.text_field :analytical_type %>
  </div>

  <div class="field">
    <%= form.label :excel_file %>
    <% if statistic.excel_file.attached? %>
      <%= statistic.excel_file.filename %><br/>
      <small><%= link_to 'Remove excel', statistic_delete_excel_attachment_path(statistic),
      method: :delete, data: { confirm: 'Are you sure?' } %></small><br/>
    <% end %>
    <%= form.file_field :excel_file %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/statistics/edit.html.erb
<h1>Editing Statistic</h1>

<%= render 'form', statistic: @statistic %>

<%= link_to 'Show', @statistic %> |
<%= link_to 'Back', statistics_path %>

app/views/statistics/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Statistics</h1>

<table>
  <thead>
    <tr>
      <th>No of treatments</th>
      <th>No of samples</th>
      <th>Analytical type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @statistics.each do |statistic| %>
      <tr>
        <td><%= statistic.no_of_treatments %></td>
        <td><%= statistic.no_of_samples %></td>
        <td><%= statistic.analytical_type %></td>
        <td><%= link_to 'Show', statistic %></td>
        <td><%= link_to 'Edit', edit_statistic_path(statistic) %></td>
        <td><%= link_to 'Destroy', statistic, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <!-- <td><%#= link_to 'Result', statistic_result_excel_analysis_path(statistic) %></td> -->
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Statistic', new_statistic_path %>

app/views/statistics/new.html.erb
<h1>New Statistic</h1>

<%= render 'form', statistic: @statistic %>

<%= link_to 'Back', statistics_path %>

app/views/statistics/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>No of treatments:</strong>
  <%= @statistic.no_of_treatments %>
</p>

<p>
  <strong>No of samples:</strong>
  <%= @statistic.no_of_samples %>
</p>

<p>
  <strong>Analytical type:</strong>
  <%= @statistic.analytical_type %>
</p>

<div class="invoice-box">
  <table cellpadding="0" cellspacing="0">
    <!-- <tr class="heading">
      <td>Item</td>
      <td class="right">Price</td>
      <td class="right">Qty</td>
      <td>Total</td>
    </tr> -->

    <% @result_data.each do |statistic_items| %>
      <tr>
        <% statistic_items.each do |item| %>
          <td>
            <%= item %>
          </td>
        <% end %>
      </tr>
    <% end %>
  </table>
</div>

<%= link_to 'Edit', edit_statistic_path(@statistic) %> |
<%= link_to 'Back', statistics_path %>